version: '3.8'

services:
  # Airflow Webserver
  airflow_webserver:
    image: apache/airflow:2.5.1
    container_name: airflow_webserver
    restart: always
    depends_on:
      - my_postgres_db
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@my_postgres_db/airflow
      AIRFLOW__CORE__FERNET_KEY: "your_fernet_key_here"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    ports:
      - "8080:8080"
    volumes:
      - airflow_data:/opt/airflow
    entrypoint: ["bash", "-c", "airflow db upgrade && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true && airflow webserver"]

  # Airflow Scheduler
  airflow_scheduler:
    <<: *airflow_base  # Используем ту же конфигурацию, но меняем команду запуска
    container_name: airflow_scheduler
    depends_on:
      - airflow_webserver
    entrypoint: ["bash", "-c", "airflow scheduler"]

volumes:
  airflow_data: